### PR TITLE
Meta kotlin

### PR DESCRIPTION
**Pull request by PinkieSwirl**

### CODE REVIEW

**Comment by Frotty** [comment]
merge?

**Comment by PinkieSwirl** [comment]
No. Have to figure out why it not builds on jitpack. From the logs I can see that the build task does not seem to trigger the compile tasks, thus no artifacts are created and thus it fails.

**Comment by PinkieSwirl** [comment]
I guess now it is mergeable. OR at least I hope it is 🥇

**Comment by PinkieSwirl** [comment]
Actually don't merge it yet. I will try to fix the history, since I did some major file moving and not all of them kept their history.

**Pull request closed without merging**
